[theme]
# Choix du thème, 'dark' ou 'light'
base = "dark"

# Couleurs principales et secondaires
primaryColor = "#00ff00"  # Vert fluo
backgroundColor = "#121212"  # Fond très sombre
secondaryBackgroundColor = "#232329"  # Fond secondaire
textColor = "#00ff00"  # Texte fluo

# Personnalisation des bordures et des ombres
borderColor = "#00ff00"  # Couleur des bordures
shadowColor = "#00ff00"  # Ombres des éléments

# Police utilisée dans l'application
font = "monospace"  # Police monospace pour un style code

# Largeur de la page
[layout]
wideMode = true
